spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate